package http

type DSP_FILE_LIST_TYPE int

const (
	DSP_FILE_LIST_TYPE_ALL DSP_FILE_LIST_TYPE = iota
	DSP_FILE_LIST_TYPE_IMAGE
	DSP_FILE_LIST_TYPE_DOC
	DSP_FILE_LIST_TYPE_VIDEO
	DSP_FILE_LIST_TYPE_MUSIC
)

const (
	TX_TYPE_ALL     = 0
	TX_TYPE_SEND    = 1
	TX_TYPE_RECEIVE = 2
)
